In [1]:
import os, re
import pandas as pd
data_path = './data_parquets/'

files = [file for file in os.listdir(data_path) if 'labeled_chunks' in file]
time_strs = [re.search(r'\d{4}-\d{2}-\d{2}_\d{6}', file).group() for file in files]
dfs = [pd.read_parquet(data_path+file) for file in files]

In [2]:
new_dfs = []
for i, df in enumerate(dfs):
    length = df.shape[0]
    df = dfs[i].copy()
    df['begin_time'] = time_strs[i]
    df['sample_id'] = df.index
    new_dfs.append(df)

all_samples = pd.concat(new_dfs, ignore_index=True)
all_samples

,ecg_raw,label,begin_time,sample_id
0,"[317, 319, 321, 321, 322, 325, 324, 324, 325, ...",bad2good,2026-02-20_010744,0
1,"[328, 331, 328, 324, 333, 362, 387, 384, 353, ...",good,2026-02-20_010744,1
2,"[330, 332, 332, 333, 334, 336, 337, 337, 337, ...",bad2good,2026-02-20_010744,2
3,"[347, 370, 412, 471, 529, 548, 512, 439, 379, ...",bad,2026-02-20_010744,3
4,"[344, 355, 364, 364, 365, 371, 381, 387, 383, ...",bad,2026-02-20_010744,4
...,...,...,...,...
19693,"[328, 329, 328, 328, 328, 328, 328, 327, 325, ...",good,2026-02-28_002011,2490
19694,"[326, 327, 327, 326, 329, 334, 339, 338, 344, ...",good,2026-02-28_002011,2491
19695,"[337, 338, 341, 342, 342, 342, 344, 348, 350, ...",good,2026-02-28_002011,2492
19696,"[320, 322, 323, 323, 321, 321, 323, 324, 324, ...",good,2026-02-28_002011,2493
19697,"[452, 412, 378, 354, 332, 315, 306, 304, 309, ...",good,2026-02-28_002011,2494

In [3]:
good = all_samples[all_samples['label'] == 'good']
bad = all_samples[all_samples['label'] == 'bad']
bad2good = all_samples[all_samples['label'] == 'bad2good']
print(good.shape[0], bad.shape[0], bad2good.shape[0])

17809 704 1185

In [18]:
bad

,ecg_raw,label,begin_time,sample_id
3,"[347, 370, 412, 471, 529, 548, 512, 439, 379, ...",bad,2026-02-20_010744,3
4,"[344, 355, 364, 364, 365, 371, 381, 387, 383, ...",bad,2026-02-20_010744,4
16,"[327, 329, 328, 328, 328, 329, 329, 328, 329, ...",bad,2026-02-20_010744,16
56,"[327, 326, 325, 325, 328, 330, 330, 327, 324, ...",bad,2026-02-20_010744,56
57,"[328, 327, 326, 326, 334, 349, 353, 336, 308, ...",bad,2026-02-20_010744,57
...,...,...,...,...
14169,"[376, 377, 374, 365, 357, 348, 344, 343, 335, ...",bad,2026-02-26_012732,2855
14175,"[268, 268, 267, 266, 267, 267, 267, 267, 267, ...",bad,2026-02-26_012732,2861
14176,"[351, 352, 354, 355, 355, 355, 356, 357, 357, ...",bad,2026-02-26_012732,2862
14177,"[337, 339, 340, 340, 340, 341, 343, 345, 346, ...",bad,2026-02-26_012732,2863
14181,"[328, 327, 327, 327, 327, 327, 327, 327, 327, ...",bad,2026-02-26_012732,2867

In [14]:
bad.describe()

         sample_id
count   403.000000
mean   1447.508685
std     940.158792
min       0.000000
25%     655.500000
50%    1165.000000
75%    2366.000000
max    3213.000000